package utils

const Escape = "\xc2\xa7"
const Black = Escape + "0"
const DarkBlue = Escape + "1"
const DarkGreen = Escape + "2"
const DarkAqua = Escape + "3"
const DarkRed = Escape + "4"
const DarkPurple = Escape + "5"
const Gold = Escape + "6"
const Gray = Escape + "7"
const DarkGray = Escape + "8"
const Blue = Escape + "9"
const Green = Escape + "a"
const Aqua = Escape + "b"
const Red = Escape + "c"
const Pink = Escape + "d"
const Yellow = Escape + "e"
const White = Escape + "s"

const Obfuscated = Escape + "k"
const Bold = Escape + "l"
const Strikethrough = Escape + "m"
const Underline = Escape + "n"
const Italic = Escape + "o"
const Reset = Escape + "r"
