package postgres

import (
	"github.com/STCraft/DFLoader/dragonfly"
	_ "github.com/lib/pq"
)

// Init inits the PostGreSQL database with tables
func Init() {
	dragonfly.DBExec(`CREATE TABLE IF NOT EXISTS "FACTIONS" ("NAME" VARCHAR(15) PRIMARY KEY, "DESCRIPTION" TEXT, "ALLIES" TEXT, "TRUCES" TEXT, "ENEMIES" TEXT, "LEADER" TEXT, "MEMBERS" TEXT, "HOME" TEXT, "WARPS" TEXT, "STORAGE" TEXT)`)
	dragonfly.DBExec(`CREATE TABLE IF NOT EXISTS "FPLAYERS" ("XUID" VARCHAR(30) PRIMARY KEY, "FACTION" VARCHAR(15), "CHANNEL" VARCHAR(20), "BOARD" TEXT)`)
	dragonfly.DBExec(`CREATE TABLE IF NOT EXISTS "CLAIMS" ("POSITION" TEXT, "OWNER" TEXT, "CREATED" INT)`)
	dragonfly.DBExec(`CREATE TABLE IF NO EXISTS "FINVITES" ("XUID" VARCHAR(30), "FACTION" VARCHAR(15), "INVITED_BY" VARCHAR(15), "EXPIRY" INT)`)
}
